# Generated by Django 4.0.7 on 2022-08-19 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomaticProcessingSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('process', models.IntegerField()),
                ('run_at', models.DateTimeField(help_text='何らかの理由で予定日時に処理を行えなかった場合は、次回のアプリケーション起動時に実行されます。', verbose_name='実行予定日時')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': '自動処理のスケジュール',
                'verbose_name_plural': '自動処理のスケジュール',
            },
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ログ作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ログ更新日時')),
                ('type', models.IntegerField()),
                ('execution_time', models.DateTimeField(blank=True, help_text='アクションがスケジュールされていてまだ完了していない場合、この値は実行予定日時を表します。', null=True, verbose_name='実行日時')),
                ('executed', models.BooleanField(blank=True, help_text='？は実行予定、×は実行中止、✓は完了を意味します。', null=True, verbose_name='実行した')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'アクションログ',
                'verbose_name_plural': 'アクションログ',
            },
        ),
    ]
